name: linting
on:
    pull_request:
        branches:
            - main
jobs:
    linting:
        strategy:
            fail-fast: true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pre-commit/action@v3.0.0

            - name: Install poetry
              run: pipx install poetry

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'
                  cache: 'poetry'

            - name: Install dependencies
              run: poetry install

            - name: Run mypy
              run: |
                  poetry run mypy anjl tests
